# See https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=
edition = "2021"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
# alignment
enum_discrim_align_threshold = 30
struct_field_align_threshold = 20
