[workspace]
resolver = "2"
members = ["vipulsabout-backend", "vipulsabout-frontend", "common"]

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"
panic = "deny"
expect_used = "deny"
